### ISSUE TITLE
Problem starting up

### ISSUE THREAD

**Issue by matjack1** [stefanoverna/generator-cc#1]
Just starting up the default stuff it throws me this error:

```
~/src/cc-test$ gulp dev
[17:58:23] Using gulpfile ~/src/cc-test/gulpfile.js
[17:58:23] Starting 'sync group0:0'...
[17:58:23] Starting 'sync group1:0'...
[17:58:23] Starting 'clean'...
[17:58:23] Finished 'clean' after 5.84 ms
[17:58:23] Finished 'sync group1:0' after 6.93 ms
[17:58:23] Starting 'sync group1:1'...
[17:58:23] Starting 'sprites'...
[17:58:23] Starting 'iconfont'...
[17:58:24] gulp-svgicons2svgfont: Font created
[17:58:24] Finished 'iconfont' after 1.16 s

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: write EPIPE
    at errnoException (net.js:904:11)
    at Object.afterWrite (net.js:720:19)
```
maybe I forgot something stupid? I'll try to debug it on Monday anyway :)

**Comment by stefanoverna** [comment]
Just to narrow down the source of problems, would you be so kind to install the latest version of the generator I just released (0.1.5)?

**Comment by matjack1** [comment]
Still no joy:

```
~/src/cc-test$ gulp dev
[12:23:56] Using gulpfile ~/src/cc-test/gulpfile.js
[12:23:56] Starting 'sync group0:0'...
[12:23:56] Starting 'sync group1:0'...
[12:23:56] Starting 'clean'...
[12:23:56] Finished 'clean' after 6.88 ms
[12:23:56] Finished 'sync group1:0' after 8.8 ms
[12:23:56] Starting 'sync group1:1'...
[12:23:56] Starting 'sprites'...
[12:23:56] Starting 'iconfont'...
[12:23:57] gulp-svgicons2svgfont: Font created
[12:23:57] Finished 'iconfont' after 1.01 s

events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: Error: spawn gm ENOENT
    at finish (/Users/matteogiaccone/src/cc-test/node_modules/gulp-image-resize/node_modules/gulp-gm/index.js:38:21)
    at gm.<anonymous> (/Users/matteogiaccone/src/cc-test/node_modules/gulp-image-resize/node_modules/async/lib/async.js:485:30)
    at gm.emit (events.js:118:17)
    at gm.<anonymous> (/Users/matteogiaccone/src/cc-test/node_modules/gulp-image-resize/node_modules/gulp-gm/node_modules/gm/lib/getters.js:70:16)
    at ChildProcess.cb (/Users/matteogiaccone/src/cc-test/node_modules/gulp-image-resize/node_modules/gulp-gm/node_modules/gm/lib/command.js:301:16)
    at ChildProcess.emit (events.js:107:17)
    at Process.ChildProcess._handle.onexit (child_process.js:1065:12)
    at child_process.js:1137:20
    at process._tickCallback (node.js:355:11)
```

here my software versions:
```
~/src/cc-test$ node -v
v0.12.0
~/src/cc-test$ npm -v
2.5.1
~/src/cc-test$ gulp -v
[12:24:49] CLI version 3.8.11
[12:24:49] Local version 3.8.11
~/src/cc-test$ yo --version
1.4.5
~/src/cc-test$ npm list -g generator-cc
/usr/local/lib
└── generator-cc@0.1.6
```

anything obvious that needs updating?

**Comment by stefanoverna** [comment]
You need to install graphicsmagick on your machine!

**Comment by matjack1** [comment]
Yes! Thanks!
